# Generated by Django 3.2.7 on 2021-10-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_modify_authors', 'Can add/edit/remove Authors'),)},
        ),
    ]
